# Generated by Django 3.1.5 on 2021-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20210108_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(height_field=100, null=True, upload_to='libros/', width_field=100),
        ),
    ]
