# Generated by Django 3.1.5 on 2021-01-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20210108_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(upload_to='libros/'),
        ),
    ]
