# Generated by Django 3.1.5 on 2021-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20210108_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(upload_to='media/libros/'),
        ),
    ]
