# Generated by Django 3.1.5 on 2021-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_auto_20210108_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, upload_to='libros/'),
        ),
    ]
