# Generated by Django 3.1.5 on 2021-01-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0012_auto_20210109_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libroautor',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='libroautor',
            name='libro',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='LibroAutor',
        ),
    ]
